version: "3.1"
services:
  node:
    build:
      context: ./nodeserver
      dockerfile: Dockerfile
    container_name: nodeserver
    volumes:
      - ./nodeserver:/nodeserver
    ports:
      - "3000"
      
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./nginx/nginx.conf:/etc/nginx/sites-available/default
    links:
      - "node"





